language: ruby
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
script:
  - bundle exec origen -v
  - bundle exec origen specs -c
  - bundle exec origen lint --no-correct
env:
  - ORIGEN_GEM_USE_FROM_SYSTEM=false ORIGEN_GEM_MANAGE_BUNDLER=false
